project:
  type: manuscript

manuscript:
  article: index.qmd
  code-links: [repo, devcontainer, binder]

format:
  html:
    theme: cosmo
    comments:
      hypothesis: true
    title-block-style: manuscript
  docx: default
  jats: default
  pdf:
    output-file: "report"
    output-ext:  "pdf"
    linkcolor: RSSblue
    urlcolor: RSSblue
    documentclass: article
    classoption: [twocolumn]
    include-in-header: 
       - "assets/styles.tex"
  typst:
    output-file: "typst-report"
    output-ext:  "pdf"
    columns: 2
    template-partials:
        - assets/typst-template.typ
        - assets/typst-show.typ
  # PrettyPDF-typst: 
  #   columns: 2
  #   papersize: iso-b3





execute:
  freeze: auto



