---
title: Pathogen Genomics Center of Excellence Situation Report
date: 4/26/2024
date-modified: today
bibliography: references.bib
---

# Key Findings

- Current data reflects a mixture of JN.1 descendents as the likely near term variants.  
- Globally no other variants with unusual characteristics have been identified as having unusual growth. 
- Some other point


# Situation Update Details

- Based on what - XYZ(?), JN.1 and descendents continue to dominate.  Some recombinations from JN.1 and other BA.5 variants are being monitoredtracked, but have yet to show significant growth relative other variants.
- Together this diversity suggests steady evolution against general population immunity with no indications of a variant driven wave of COVID-19 infections. 
- As of MM/DD/YYYY, there were X samples from MM/DD/YYYY - MM/DD/YYYY, some comment on trend
- Some text here about image one. There is this variant that's here
- Some text about image two
- Image 3 has this
- Findings from a site's analysis of national data

# Background 

To monitor SARS-CoV-2 in Washington state, Washington state Department of Health (WA DOH) implemented a Sentinel Surveillance system, a type of genomic surveillance that tracks SARS-CoV-2 variants across the state. Laboratories across the state, including the Washington state Public Health Laboratories (PHL) will sequence SARS-CoV-2 from collected specimens. Raw sequencing data is assembled into consensus genomes using publicly available bioinformatics pipeline, and the consensus genomes are uploaded to public repositories like GISAID and GenBank. This report demonstrates how the NW PGCoE utilizes SARS-CoV-2 sequencing data to monitor emerging variants biweekly, forecast emerging SARS-CoV-2 variants, and infers relative abundance estimates of SARS-CoV-2 variants in the wastewater. Previous work that looked at the disease severity of SARS-CoV-2 variants is currently being implemented to analyze the disease severity of current variants utilizing hospitalization data. This work is ongoing and will be presented at a later time.

## Section
This is a simple placeholder for the manuscript's main document [@knuth84].
